"""add anonymized text and recruiter status to resumes

Revision ID: 017464b277d3
Revises: d152c6310932
Create Date: 2026-07-20 13:36:21.636320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017464b277d3'
down_revision: Union[str, Sequence[str], None] = 'd152c6310932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('anonymized_text', sa.Text(), nullable=False, server_default=''))
    op.add_column('resumes', sa.Column('recruiter_status', sa.String(length=20), nullable=False, server_default='new'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'recruiter_status')
    op.drop_column('resumes', 'anonymized_text')
    # ### end Alembic commands ###
