"""add job retry and progress tracking

Revision ID: d152c6310932
Revises: a19d6723885d
Create Date: 2026-07-20 13:20:18.036631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd152c6310932'
down_revision: Union[str, Sequence[str], None] = 'a19d6723885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('rq_job_id', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('processing_jobs', sa.Column('progress_message', sa.String(length=200), nullable=False, server_default='Queued'))
    op.add_column('processing_jobs', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('processing_jobs', sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'max_attempts')
    op.drop_column('processing_jobs', 'attempts')
    op.drop_column('processing_jobs', 'progress_message')
    op.drop_column('processing_jobs', 'progress')
    op.drop_column('processing_jobs', 'rq_job_id')
    # ### end Alembic commands ###
